project:
  name: 'NLP_Disaster_Tweets'
  dir: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/NLP_Disaster_Tweets'

sys:
  fig_size_m: [20,15]
  fig_size_l: [12,12]

data:
  raw_data_train: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/NLP_Disaster_Tweets/Data/A_Raw/train.csv'
  raw_data_test: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/NLP_Disaster_Tweets/Data/A_Raw/test.csv'

  sdo_parq: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/NLP_Disaster_Tweets/Data/Serialised_Data_Objects/Parq'
  sdo_pkl: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/NLP_Disaster_Tweets/Data/Serialised_Data_Objects/Pkl'

subdirs:
  - 'utils'
  - 'Modularization'
  - 'Scripts'



# Pipeline Parameters
raw_dtype:
    'id': 'int64'
    'keyword': 'object'
    'location': 'object'
    'text': 'object'
    'target': 'int64'

true_dtype:
    'id': 'int64'
    'keyword': 'object'
    'location': 'object'
    'text': 'object'
#    'target': 'int64'

dd_descriptions:
    'id': 'Unique identifier for each tweet'
    'keyword': 'Keyword from the tweet'
    'location': 'Location the tweet was sent from'
    'text': 'Text of the tweet'
    'target': 'Whether the tweet is about a real disaster (1) or not (0)'
  
pipeline_parameters:
  drop_cols: ['location']
  text_col: 'text'
